# Another file that tells the AWS computer what to do and how to build your application
version: 0.2

phases:
  # phase used to install all the necesarry dependencies
  # install:
  #   commands:
  #     - echo 'Installing dotNet 6'
  #     - /usr/local/bin/dotnet-install.sh --channel LTS
  
  # pre_build:
  #   commands:
  #     - echo 'Restoring dependencies of each project (the packages) and unit testing'
  #     - cd backend
  #     - dotnet restore
  #     - dotnet test --no-restore
  
  build:
    commands:
        - echo 'Passing files to AWS elastic beanstalk'
  #     - echo 'Building the app'
  #     - cd backend
  #     - dotnet build
  
  # post_build:
  #   commands:
  #     - echo 'Creating the publish folder for the app'
  #     - cd backend
  #     - dotnet publish -c Release -o publish

artifacts:
  files:
    - 'Dockerrun.aws.json'
    - 'docker-compose.yml'
    - 'backend/**/*'
    - 'frontend/**/*'
  
