services:
  backend:
    build: ./backend
    image: netbackend
    environment:
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - 5001:5001
  
  frontend:
    build: ./frontend
    image: reactbackend
    ports:
      - 5000:80
    depends_on:
      - backend